Tidy up and extension of field activities (work records)
Datalinker-Org/Geospatial pull request #43
Opened 2022-08-30 01:57 UTC by cookeac

* Restructure measurements to have a base type (`MeasurementType`), and specific concrete types that specify unit enumerations.
* Added volume and mass units for product applications
* Add solar irradiance type and remove climate measurement type
* Move `OperationRecordResource` and `WorkRecordResource` to the resources folder
* Lint and correct some typos

2022-08-31 04:46 UTC, danielR9 requested changes
The movement of types to resources has not changed the `$id` of them. So `resources/WorkRecordResource.json` has an id with `types/WorkRecordResource.

Same for other types that have been moved to resources directory

There is also inconsistence in the id naming conventions some are `types/IrradianceMeasureType` and others are `types/humidityMeasure`. Both with case, and the use of `Type` as a suffix

2022-08-31 04:46 UTC, danielR9 commented on types/MeasurementType.json
> +    "$id": "/types/AreaMeasureType",
Don't think this id is correct if this is the base measurement type?

2022-08-31 04:46 UTC, danielR9 commented on types/SpatialMeasureType.json
> +
Missing `$id`?

2022-08-31 08:35 UTC, cookeac commented
@danielR9 I've corrected the $id values (all I could see), but I recall why the older Geospatial files and the newer ones I've created don't have the "$schema" and "$id" values.

We incorporate these into OAS3 OpenAPI (Swagger) files and OAS3 only seems to allow one $schema declaration per OAS3 file. This means any linting tool for OAS3 will give errors if each of the files included with $ref also contain a schema declaration.

I don't know for sure why it doesn't like $id, but similarly OAS3 linting tools seem to think you use it as a base for resolving local relative references, and give an error if you have then in each file. 

Do we use these for anything in any build processes? Otherwise I think we're better to remove them, and just specify the $schema in the example OAS3 URL schemes.

2022-09-06 01:32 UTC, chriiiish commented on resources/WorkRecordResource.json
> +        "nonOverlapArea": {
Consider renaming this?
```suggestion
        "nonOverlapWorkedArea": {
```

2022-09-06 02:34 UTC, merged